name: Update updatedAt date

on:
  push:
    paths:
      - "**/*.md"

jobs:
  update-date:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if .md files have changed
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.md$' || echo "No markdown files changed"

      - name: Update updatedAt in .md files
        run: |
          for file in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.md$'); do
            echo "Updating updatedAt in $file"
            sed -i "s/updatedAt: [0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}/updatedAt: $(date +%Y-%m-%d)/" $file
          done

      - name: Commit changes if any
        run: |
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git config user.name "github-actions"
            git config user.email "github-actions@users.noreply.github.com"
            git add .
            git commit -m "Update updatedAt field in modified files"
            git push
          fi
